/**
 * @author Altimetrik
 * @description
 *  started on MM/DD/YYYY
 *  REPLACE_BY_CLASS_LOGIC_RESPONSABILITIES
 **/
public with sharing class aqi_WrapperCtrl {
    // Constants

    //************************************************************************
    // Properties & data members



    //************************************************************************
    // Methods

    public aqi_WrapperCtrl() {
        
    }

    /*
    * @description
    *   WHAT_THE_METHOD_DOES
    * @params
    *   DATA_TYPE PARAM_NAME PARAM_USED_FOR
    * @return 
    *   DATA_TYPE 
    */
    //public DATA_TYPE some_method(DATA_TYPE, PARAM_NAME){}



}